apiVersion: v1
kind: Service
metadata:
  name: facerecognizer-srv
  labels:
    run: facerecognizer-srv
spec:
  #type: NodePort
  #type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
    #nodePort: 30002
  selector:
    run: facerecognizer-test
---
apiVersion: v1
kind: Service
metadata:
  name: facerecognizer-topz
  labels:
    run: topz
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: topz
  selector:
    run: facerecognizer-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: facerecognizer-test
spec:
  selector:
    matchLabels:
      run: facerecognizer-test
  replicas: 1
  template:
    metadata:
      labels:
        run: facerecognizer-test
    spec:
      shareProcessNamespace: true
      containers:
      - name: facerecognizer-test
        image: 192.168.122.1:5000/face_recognizer:1.0.1
        ports:
        - containerPort: 5000
        resources:
          limits:
             nvidia.com/gpu: 1
        securityContext:
          privileged: true
        volumeMounts:
          - name: tmp
            mountPath: /tmp/test
          - name: x11
            mountPath: /tmp/.X11-unix
          - name: xauthority
            mountPath: /root/.Xauthority
          - name: dev-video0
            mountPath: /dev/video0
      - name: topz
        image: kalise/topz:latest
        ports:
          - containerPort: 8080
        command:
          - /server
        args:
          - -addr
          - 0.0.0.0:8080
      volumes:
        - name: tmp
          hostPath:
            path: /mnt
        - name: x11
          hostPath:
            path: /tmp/.X11-unix
        - name: xauthority
          hostPath:
            path: /root/.Xauthority
        - name: dev-video0
          hostPath:
            path: /dev/video0
